name: fmt

on:
  workflow_dispatch:

jobs:
  format-and-build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: refs/heads/${{ github.event.inputs.branch }}

      # Using the requested deprecated toolchain action
      - name: Install Rust Toolchains
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
          
      # Using the requested cache action
      - name: Cache Rust Build Artifacts
        uses: Swatinem/rust-cache@v2

      - name: Run cargo fmt
        run: cargo fmt --all

      - name: Run cargo build
        run: cargo build --verbose

      - name: Commit and Push Formatted Changes
        if: success()
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name 'github-actions[bot]'
            git config user.email 'github-actions[bot]@users.noreply.github.com'
            git add .
            git commit -m "fmt"
            git push origin ${{ github.event.inputs.branch }}
          fi
